[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
]

[tool.mypy]
plugins = [
    "numpy.typing.mypy_plugin",
    "pydantic.mypy",
]

[tool.ruff]
fix = true
force-exclude = true
ignore = [
    "PLR0913",
    "S101",
    "N806",
]
select = [
    "A",
    "B",
    "C",
    "DTZ",
    "E",
    "EM",
    "F",
    "FBT",
    "I",
    "ICN",
    "ISC",
    "N",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "Q",
    "RUF",
    "S",
    "SIM",
    "T",
    "TID",
    "UP",
    "W",
    "YTT",
]
isort.known-first-party = ["btrack"]
mccabe.max-complexity = 18

[tool.setuptools_scm]

[tool.tomlsort]
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
